### ISSUE TITLE
Gerber

### ISSUE THREAD

**Issue by nbgsmk** [pms67/LittleBrain-STM32F4-Sensorboard#1]
Hello friend! 
I found your youtube video on stm32 and I thought, let's give it a try! I also wanted to see how it looks in jlcpcb's ordering tool, and to perfect the process, as I am not experienced with pcb fabs. But after uploading gerber files to jlcpcb (I used the provided .rar), the board dimensions are not detected (both fields are empty) and there is no board-preview, as usual. Therefore, the option of their smt assembly is not enabled. Do you know what could be the issue? Thanks!

**Comment by pms67** [comment]
Hey there,
That's strange - I just tried uploading the files again myself and everything appears as it should.

![image](https://user-images.githubusercontent.com/34550389/97460611-34889d80-193d-11eb-8268-689eb31dd2f7.png)

Maybe some sort of browser issue?

**Comment by nbgsmk** [comment]
Hello again!
You're right! Somehow. :)  Ofcourse, I tried twice in the morning, and twice again this evening. And this time it works. But it's the same browser as before. So I'm thinking maybe because I restarted Firefox due to update, or it was some issue on their site. No big deal...actually I learned it is worth waiting and trying, eg. on the following day. Thanks for your quick reply! You can close the issue.
Zoran
