### ISSUE TITLE
MP2359 now end of life at JLCPCB

### ISSUE THREAD

**Issue by m1geo** [pms67/LittleBrain-STM32F4-Sensorboard#3]
Just to let you know that the MP2359DJ-LF-Z is no longer stocked at JLCPCB or LCSC.
![image](https://user-images.githubusercontent.com/758615/109810575-9cb7fa80-7c21-11eb-8ea2-47895078366d.png)

**Comment by pms67** [comment]
Hi there, Thanks - I'm making an updated version of this board with different components. Will make a new video, once I have it in my hands. :)
